SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT * p.PRICE) as SALES
FROM PRODUCT as p INNER JOIN OFFLINE_SALE as o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;