WITH MY_T AS (
SELECT AI.ANIMAL_ID, AI.NAME, DATEDIFF(AO.DATETIME, AI.DATETIME) as DF
FROM ANIMAL_INS as AI LEFT JOIN ANIMAL_OUTS as AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NOT NULL
ORDER BY DF DESC
LIMIT 2 )


SELECT ANIMAL_ID, NAME
FROM MY_T;
