WITH MY_T AS (SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE)


SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO as RI, MY_T
WHERE RI.FOOD_TYPE = MY_T.FOOD_TYPE AND RI.FAVORITES = MY_T.FAVORITES
ORDER BY FOOD_TYPE DESC;