SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') START_DATE,
DATE_FORMAT(END_DATE, '%Y-%m-%d') END_DATE, IF(DATEDIFF(DATE_FORMAT(END_DATE, '%Y-%m-%d'), DATE_FORMAT(START_DATE, '%Y-%m-%d')) + 1  < 30, '단기 대여', '장기 대여') as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09-%'
ORDER BY HISTORY_ID DESC;