WITH MY_T AS ( SELECT HOST_ID, COUNT(HOST_ID) as C
FROM PLACES
GROUP BY HOST_ID )

SELECT ID, NAME, P.HOST_ID
FROM PLACES as P INNER JOIN MY_T ON P.HOST_ID = MY_T.HOST_ID
WHERE MY_T.C >= 2
ORDER BY ID;