# SELECT * FROM ANIMAL_OUTS;

# SELECT 
# CASE WHEN HOUR(DATETIME) = ''

WITH MY_T AS (
SELECT HOUR(DATETIME) as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
)

SELECT HOUR, COUNT
FROM MY_T
WHERE HOUR BETWEEN 9 AND 19
ORDER BY HOUR;