SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AS AI INNER JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
# WHERE DATEDIFF(AO.DATETIME, AI.DATETIME) < 0
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME ASC;